name: Static (bionic amd64)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3     
     
    - name: Install depedencies
      run: |
         sudo apt-get update
         sudo apt install -y cmake git ca-certificates ninja-build ccache g++-8 autoconf automake make file libtool pkg-config patch openssh-client
         git submodule update --init --recursive
    - name: Build
      run: |
         mkdir build
         cd build
         cmake .. -G Ninja -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always -DCMAKE_BUILD_TYPE=Release -DLOCAL_MIRROR=https://oxen.rocks/deps -DUSE_LTO=ON -DBUILD_TESTS=OFF -DBUILD_STATIC_DEPS=ON -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8
         ninja -j6 -v   
         ninja strip
         ninja create_zip
         pwd
         ls
